language: python
sudo: false
dist: trusty

python:
  - '2.7'
  - '3.5'
  - '3.6'
  - 'nightly'

matrix:
  allow_failures:
    - python: 'nightly'

before_install:
  - pip install --quiet --upgrade pip setuptools

install:
  - |
    pip install --quiet \
        coveralls \
        "pytest>=2.8" \
        "mock ; python_version < '3'"
  - pip install -r requirements-doc.txt
  - pip install --editable .

script:
  - coverage run ./setup.py test
  - coverage run --append `which gwtrigfind` --help
  - python setup.py build_sphinx -W

after_success:
  - coveralls

before_cache:
  - rm -f ${HOME}/.cache/pip/log/debug.log

cache:
  pip: true
