language: python

addons:
  apt:
    sources:
      - sourceline: deb http://software.ligo.org/lscsoft/debian wheezy contrib
        key_url: http://software.ligo.org/keys/deb/lscsoft.key
      - sourceline: deb-src http://software.ligo.org/lscsoft/debian wheezy contrib
        key_url: http://software.ligo.org/keys/deb/lscsoft.key
    packages:
      - pkg-config  # lal
      - zlib1g-dev  # lal
      - libgsl0-dev  # lal
      - swig  # lal
      - bc  # lal
      - libfftw3-dev  # lal

env:
  global:
    - LAL_VERSION="6.18.0"

matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: nightly
      env: PRE="--pre"
  allow_failures:
    - python: 3.5
    - python: nightly
      env: PRE="--pre"

before_install:
  - pip install -q --upgrade ${PRE} pip
  - pip install -q --upgrade ${PRE} coveralls "pytest>=2.8" unittest2 mock
  - pip install -q --upgrade ${PRE} numpy  # for lal
  - .travis/build-lal.sh

install:
  - pip install ${PRE} -r requirements.txt
  - pip install .

script:
  - coverage run --source=trigfind --omit="trigfind/_version.py" ./setup.py test
  - coverage run --append --source=trigfind --omit="trigfind/_version.py" `which trigfind` --help

after_success:
  - coveralls

cache:
  apt: true
  pip: true
  directories:
    - lal-${LAL_VERSION}

before_cache:
  - rm -f ${HOME}/.cache/pip/log/debug.log
  - rm -f ./lal-${LAL_VERSION}/config.log
